# Generated by Django 4.2 on 2023-04-17 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mars_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
